version: '3.8'
services:
  nginx:
    image: 'nginx:stable-alpine'
    container_name: nginx-server
    restart: always
    ports:
      - '8888:80'
    volumes:
      - '.:/var/www/html'
      # - ./dockerfiles/nginx/default.conf/:/etc/nginx/conf.d/
    depends_on:
      - main
      - db
    networks:
      - common_network
  main:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - '.:/var/www/html'
    ports:
      - '8000:8000'
      - "5173:5173"
    depends_on:
      - db
    networks:
      - common_network
  db:
    image: 'mysql:5.7.22'
    # image: 'mysql:8.2'
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: quorumitdb_laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - './db-data:/var/lib/mysql'
      # - ./dockerfiles/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - '3306:3306'
    networks:
      - common_network

  node:
    image: 'node:16'
    container_name: node_vite
    working_dir: /var/www/html
    volumes:
      - './:/var/www/html'
      - /var/www/html/node_modules
    command: 'sh /var/www/html/node_start.sh'
    depends_on:
      - main
    networks:
      - common_network

networks:
  common_network:
    driver: bridge
volumes:
  db-data:
    driver: local
